version: "3.8"

services:
  cisco-backup:
    
    build: .
    
  
    image: cisco-switch-backup:1.0

    volumes:
      
      - ./hosts.yml:/ansible/inventory.yml:ro

      - ./group_vars:/ansible/group_vars:ro 

     
      - ./backups:/media/sf_My_App


    restart: "no"
