all:
  children:
    switches:
      children:

        ground_floor:
          hosts:
            G-Floor-Sw1:
              ansible_host: 192.168.100.4
            G-Floor-Sw2:
              ansible_host: 192.168.100.7
            G-Floor-Sw3:
              ansible_host: 192.168.100.8

        second_floor:
          hosts:
            2nd-Floor-Sw1:
              ansible_host: 192.168.100.2
            2nd-Floor-Sw2:
              ansible_host: 192.168.100.3
            2nd-Floor-Sw3:
              ansible_host: 192.168.100.5
            2nd-Floor-Sw4:
              ansible_host: 192.168.100.6
            2nd-Floor-Sw5:
              ansible_host: 192.168.100.9
